apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osg-head-storage
  namespace: osg
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi


