apiVersion: apps/v1
kind: Deployment
metadata:
  name: osg-head-prp-sdsc
  namespace: osg
  labels: 
    k8s-app: osg-head-prp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: osg-head-prp
  template:
    metadata: 
      labels:
        k8s-app: osg-head-prp
    spec:
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/stashcache
        operator: Exists
      nodeSelector: 
        kubernetes.io/hostname: xcache-11.t2.ucsd.edu
      containers:
      - name: osg-head-prp
        image: sfiligoi/prp-osg-head
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        resources:
           limits:
             memory: 16Gi
             cpu: 4
           requests:
             memory: 4Gi
             cpu: 1
        volumeMounts:
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
        - name: ceph
          mountPath: /mnt/ceph
        - name: configpasswd
          mountPath: /var/lock/condor/pool_password
          subPath: pool_password
          readOnly: true
        - name: configinit
          mountPath: /etc/osg/image-config.d/80_pod_init.sh
          subPath: 80_pod_init.sh
          readOnly: true
        - name: configosg10
          mountPath: /etc/osg/config.d/01-squid.ini
          subPath: 01-squid.ini 
        - name: configosg30
          mountPath: /etc/osg/config.d/30-gip.ini
          subPath: 30-gip.ini
        - name: configosg40
          mountPath: /etc/osg/config.d/40-siteinfo.ini
          subPath: 40-siteinfo.ini
        - name: configgridmap
          mountPath: /etc/grid-security/grid-mapfile
          subPath: grid-mapfile
      volumes:
      - name : hostcert
        hostPath:
           path: /etc/grid-security/hostcert.pem
           type: File
      - name : hostkey
        hostPath:
           path: /etc/grid-security/hostkey.pem
           type: File
      - name: ceph
        persistentVolumeClaim:
          claimName: osg-head-storage
      - name: configpasswd
        secret:
          secretName: osg-head-prp-sdsc-config
          items:
             - key: pool_password
               path: pool_password
          defaultMode: 256
      - name: configinit
        secret:
          secretName: osg-head-prp-sdsc-config
          items:
             - key: 80_pod_init.sh
               path: 80_pod_init.sh
          defaultMode: 365
      - name: configosg10
        secret:
          secretName: osg-head-prp-sdsc-config
          items:
             - key: 01-osg-squid.ini
               path: 01-squid.ini
          defaultMode: 292
      - name: configosg30
        secret:
          secretName: osg-head-prp-sdsc-config
          items:
             - key: 30-osg-gip.ini
               path: 30-gip.ini
          defaultMode: 292
      - name: configosg40
        secret:
          secretName: osg-head-prp-sdsc-config
          items:
             - key: 40-osg-siteinfo.ini
               path: 40-siteinfo.ini
          defaultMode: 292
      - name: configgridmap
        secret:
          secretName: osg-head-prp-sdsc-config
          items:
             - key: grid-mapfile
               path: grid-mapfile
          defaultMode: 292

