apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: osg-head-prp-sdsc
  namespace: osg
  labels: 
    k8s-app: osg-head-prp
spec:
  template:
    metadata: 
      labels:
        k8s-app: osg-head-prp
    spec:
      hostNetwork: true
      nodeSelector: 
        kubernetes.io/hostname: xcache-11.t2.ucsd.edu
      containers:
      - name: osg-head-prp
        image: sfiligoi/prp-osg-head
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        volumeMounts:
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
        - name: condordata
          mountPath: /var/lib/condor
        - name: homedata
          mountPath: /home
        - name: configpasswd
          mountPath: /var/lock/condor/pool_password
          subPath: pool_password
          readOnly: true
        - name: configinit
          mountPath: /usr/bin/pod_init.sh
          subPath: pod_init.sh
          readOnly: true
        - name: configosg30
          mountPath: /etc/osg/config.d/30-gip.ini
          subPath: 30-gip.ini
          readOnly: true
        - name: configosg40
          mountPath: /etc/osg/config.d/40-siteinfo.ini
          subPath: 40-siteinfo.ini
          readOnly: true
        - name: configgridmap
          mountPath: /etc/grid-security/grid-mapfile
          subPath: grid-mapfile
      volumes:
      - name : hostcert
        hostPath:
           path: /etc/grid-security/hostcert.pem
           type: File
      - name : hostkey
        hostPath:
           path: /etc/grid-security/hostkey.pem
           type: File
      - name: condordata
        hostPath:
          path: /var/run/condor-ce-prp/condor_spool
          type: Directory
      - name: homedata
        hostPath:
          path: /var/run/condor-ce-prp/users_home
          type: Directory
      - name: configpasswd
        secret:
          secretName: osg-head-prp-sdsc-config
          items:
             - key: pool_password
               path: pool_password
          defaultMode: 256
      - name: configinit
        secret:
          secretName: osg-head-prp-sdsc-config
          items:
             - key: pod_init.sh
               path: pod_init.sh
          defaultMode: 365
      - name: configosg30
        secret:
          secretName: osg-head-prp-sdsc-config
          items:
             - key: 30-osg-gip.ini
               path: 30-gip.ini
          defaultMode: 292
      - name: configosg40
        secret:
          secretName: osg-head-prp-sdsc-config
          items:
             - key: 40-osg-siteinfo.ini
               path: 40-siteinfo.ini
          defaultMode: 292
      - name: configgridmap
        secret:
          secretName: osg-head-prp-sdsc-config
          items:
             - key: grid-mapfile
               path: grid-mapfile
          defaultMode: 292

